#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#define FILENAME_LEN (1<<8)
#define STRING_BUFFER_SIZE (1<<10)
#define TILE_SIZE (1<<8)
#define TILE_SIZE2 (TILE_SIZE * TILE_SIZE)
#define TEXTURE_BUFFER_SIZE (TILE_SIZE<<1)
#define TEXTURE_BUFFER_SIZE2 (TEXTURE_BUFFER_SIZE * TEXTURE_BUFFER_SIZE)
#define RADIUS (6378137.0)

#endif
